# Change these first
owner: klue-kr # Your GitHub organization or username, where this repository lives
repo: klue-uptime # The name of this repository

sites:
  - name: KLUE
    url: https://klue.kr
  - name: KLUE API
    url: https://api-external.klue.kr/api/health

status-website:
  baseUrl: /klue-uptime
  logoUrl: https://klue.kr/favicon.ico
  name: KLUE
  navbar:
    - title: Status
      href: /klue-uptime
    - title: GitHub
      href: https://github.com/klue-kr
    - title: Contact
      href: mailto://klueask@gmail.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
